---
title: "STATS 506 HW 5"
author: "Calder Moore"
format: pdf
editor: visual
---

## Problem 1 - OOP Programming

### a)

```{r}
setClass("waldCI",
         slots = c(level = "numeric",
                   mean = "numeric",
                   sterr = "numeric",
                   lb = "numeric",
                   ub = "numeric"))

#Validator
setValidity("waldCI", function(object){
  if (!(object@level >= 0 & object@level <= 1)) {
    stop(paste("@level = ", object@level, "is not in the range (0,1)"))
  }
  else if (object@sterr < 0){
    stop(paste("@sterr = ", object@sterr, "is negative"))
  }
  else if (object@lb > object@ub){
    stop(paste("@lb = ", object@lb, "is greater than the upper bound"))
  }
  else if (object@lb == Inf){
    stop(paste("@lb = ", object@lb, "is infinity"))
  }
  else if (object@ub == Inf){
    stop(paste("@ub = ", object@ub, "is infinity"))
  }
  return(TRUE)
})

#show method
setMethod("show", "waldCI",
  function(object) {
    cat(paste0("(", object@lb, ", ", object@ub, ")"))
    return(invisible(object))
  }
)

#accessors
setGeneric("level", function(object){
  standardGeneric("level")}
  )
setMethod("level", "waldCI", function(object){
  return(slot(object, "level"))})

setGeneric("mean", function(object){
  standardGeneric("mean")}
  )
setMethod("mean", "waldCI", function(object){
  return(slot(object, "mean"))})

setGeneric("sterr", function(object){
  standardGeneric("sterr")}
  )
setMethod("sterr", "waldCI", function(object){
  return(slot(object, "sterr"))})

setGeneric("lb", function(object){
  standardGeneric("lb")}
  )
setMethod("lb", "waldCI", function(object){
  return(slot(object, "lb"))})

setGeneric("ub", function(object){
  standardGeneric("ub")}
  )
setMethod("ub", "waldCI", function(object){
  return(slot(object, "ub"))})

#setters
setGeneric("level<-",
           function(object, value) {
             standardGeneric("level<-")
           })
setMethod("level<-", "waldCI",
  function(object, value) {
    object@level <- value
    validObject(object)
    return(object)
})

setGeneric("mean<-",
           function(object, value) {
             standardGeneric("mean<-")
           })
setMethod("mean<-", "waldCI",
  function(object, value) {
    object@mean <- value
    validObject(object)
    return(object)
})

setGeneric("sterr<-",
           function(object, value) {
             standardGeneric("sterr<-")
           })
setMethod("sterr<-", "waldCI",
  function(object, value) {
    object@sterr <- value
    validObject(object)
    return(object)
})

setGeneric("lb<-",
           function(object, value) {
             standardGeneric("lb<-")
           })
setMethod("lb<-", "waldCI",
  function(object, value) {
    object@lb <- value
    validObject(object)
    return(object)
})

setGeneric("ub<-",
           function(object, value) {
             standardGeneric("ub<-")
           })
setMethod("ub<-", "waldCI",
  function(object, value) {
    object@ub <- value
    validObject(object)
    return(object)
})

#contains method
setGeneric("contains",
           function(object, value) {
             standardGeneric("contains")
           })
setMethod("contains", "waldCI",
  function(object, value) {
    value >= object@lb & value <= object@ub
})

#overlap method
setGeneric("overlap",
           function(object1, object2) {
             standardGeneric("overlap")
           })
setMethod("overlap", "waldCI",
  function(object1, object2) {
    max(object1@lb, object2@lb) <= min(object1@ub, object2@ub)
})

#as.numeric method
setMethod("as.numeric", "waldCI", function(x){c(x@lb, x@ub)})

#transformCI method
setGeneric("transformCI",
           function(object, func) {
             standardGeneric("transformCI")
           })
setMethod("transformCI", "waldCI",
  function(object, func) {
    warning("Only monotonic transformations are sensible.")
    new("waldCI",
        level = object@level,
        mean = func(object@mean), 
        sterr = abs(func(object@mean + object@sterr) - func(object@mean)), #use f(a+b)-f(a) to approximate f'(a)
        lb = func(object@lb), 
        ub = func(object@ub))
})

#function
waldCI <- function(level, mean = NULL, sterr = NULL, lb = NULL, ub = NULL){
  if(!is.numeric(level) | level <= 0 | level >= 1){
    stop("level must be between 0 and 1.")
  }
  
  #determine alpha level for confidence level
  alpha <- 1 - level
  z <- qnorm(1 - alpha/2)
  
  #check for null values depending on if user uses mean/sterr or bounds
  if (!is.null(mean) & !is.null(sterr)) {
    lb <- mean - z*sterr
    ub <- mean + z*sterr
  } else if (!is.null(lb) & !is.null(ub)) {
    mean <- (lb + ub) / 2
    sterr <- (ub - lb) / (2*z)
  } else {
    stop("Provide either mean and sterr or a lower and upper bound.")
  }

  new("waldCI", level = level, mean = mean, sterr = sterr, lb = lb, ub = ub)
}
```

### b)

Now create three objects to test.

```{r}
ci1 <- waldCI(level = 0.95, lb = 17.2, ub = 24.7)
ci2 <- waldCI(level = 0.99, mean = 13, sterr = 2.5)
ci3 <- waldCI(level = 0.75, lb = 27.43, ub = 39.22)
```

Code evaluation:

```{r}
ci1
ci2
ci3
as.numeric(ci1)
as.numeric(ci2)
as.numeric(ci3)
lb(ci2)
ub(ci2)
mean(ci1)
sterr(ci3)
level(ci2)
lb(ci2) <- 10.5
mean(ci3) <- 34
level(ci3) <- .8
contains(ci1, 17)
contains(ci3, 44)
overlap(ci1, ci2)
eci1 <- transformCI(ci1, sqrt)
eci1
mean(transformCI(ci2, log))
```
### c)

```{r, eval=FALSE}
waldCI(level = 0.95, mean = 0, sterr = -2)
```
```{r, eval=FALSE}
waldCI(level = 0.95, lb = 2, ub = 1)
```

```{r, eval=FALSE}
waldCI(level = 0.95, lb = -Inf, ub = Inf)
```

```{r, eval=FALSE}
waldCI(level = 0.95, mean = "c", sterr = "hello")
```

## Problem 2 - Plotly






